/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewIndexRouteImport } from './routes/preview/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'

const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: '/preview/',
  path: '/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/editor': typeof EditorIndexRoute
  '/preview': typeof PreviewIndexRoute
}
export interface FileRoutesByTo {
  '/editor': typeof EditorIndexRoute
  '/preview': typeof PreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/editor/': typeof EditorIndexRoute
  '/preview/': typeof PreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/editor' | '/preview'
  fileRoutesByTo: FileRoutesByTo
  to: '/editor' | '/preview'
  id: '__root__' | '/editor/' | '/preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EditorIndexRoute: typeof EditorIndexRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/preview/': {
      id: '/preview/'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EditorIndexRoute: EditorIndexRoute,
  PreviewIndexRoute: PreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
