/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorIndexRouteImport } from './routes/editor/index'

const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/editor': typeof EditorIndexRoute
}
export interface FileRoutesByTo {
  '/editor': typeof EditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/editor/': typeof EditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/editor'
  fileRoutesByTo: FileRoutesByTo
  to: '/editor'
  id: '__root__' | '/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EditorIndexRoute: typeof EditorIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/editor/': {
      id: '/editor/'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  EditorIndexRoute: EditorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
